apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: project-id #project id
build:
  artifacts:
    #Local configuration
    # Client context of React
    - image: org_name/project_name/client-servicename
      context: client-service-folder
      sync:
        manual:
          - src: ./src/**/*.ts
            dest: .
          - src: "***/*.html"
            dest: .
          - src: "***/*.css"
            dest: .
      docker:
        dockerfile: Dockerfile
    # Service 1 context
    - image: org_name/project_name/servicename
      context: service-folder #folder where codebase is stored
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: org_name/project_name/servicename2
      context: service2-folder
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    sha256: {} #this  tag policy uses the tag latest of image
  #Local configuration
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s-dev/*
deploy:
  kubectl: {}
