apiVersion: v1
kind: Secret
metadata:
  name: shared-secrets
data:
  #JWT CONFIGURATION
  JWT_KEY: <base64-base64-value>
  SECRET: <base64-base64-value>

  #MONGODB CONFIGURATION:
  MONGO_URI: <base64-value>
  MONGO_URI_TEST: <base64-value>

  #GOOGLE CLOUD CONFIGURATION
  GOOGLE_PROJECT_ID: <base64-value>
  GOOGLE_CLOUD_PROJECT: <base64-value>
  GOOGLE_STORAGE_BUCKET_NAME: <base64-value>
  GOOGLE_CLIENT_ID: <base64-value>
  GOOGLE_CLIENT_SECRET: <base64-value>
  GOOGLE_MAPS_API_KEY: <base64-value>

  #SPARKPOST CONFIGURATION
  SPARKPOST_API_KEY: <base64-value> #Use test key here
  SPARKPOST_SENDER_DOMAIN: <base64-value>

  # MESSAGEBIRD CONFIGURATION
  MESSAGEBIRD_ACCESS_KEY: <base64-value> #Use test key here
  MESSAGEBIRD_WHATSAPP_CHANNEL_ID: <base64-value>
  MESSAGEBIRD_TEMPLATE_NAMESPACE_ID: <base64-value>
  MESSAGEBIRD_TEMPLATE_NAME_TEST: <base64-value>

  #MYSQL CONFIGURATION SECRECTS
  MYSQL_HOST_STAGE: <base64-value>
  MYSQL_USER_STAGE: <base64-value>
  MYSQL_PASSWORD_STAGE: <base64-value>
  MYSQL_DB_STAGE: <base64-value>
  MYSQL_SOCKET_STAGE: <base64-value> #not necessary

  MYSQL_HOST_PROD: <base64-value>
  MYSQL_USER_PROD: <base64-value>
  MYSQL_PASSWORD_PROD: <base64-value>
  MYSQL_DB_PROD: <base64-value>
  MYSQL_SOCKET_PROD: <base64-value> #not necessary


  #kubectl create secret generic jwt-secret --from-literal=JWT_KEY=JWT_SECRET

  #Don't forget to create the google-application-credentials secret with
  #kubectl create secret generic google-application-credentials --from-file=google-application-credentials.json=./google-application-credentials.json
