# SKAFFOLD CONFIGURATION FOR PRODUCTION
apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: project-id #project id
build:
  artifacts:
    # Client context of React
    - image: europe-west1-docker.pkg.dev/your_artifact_url/client-servicename
      context: client-service
      sync:
        manual:
          - src: ./src/**/*.ts
            dest: .
          - src: "***/*.html"
            dest: .
          - src: "***/*.css"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: europe-west1-docker.pkg.dev/your_artifact_url/servicename
      context: service-folder
      sync:
        manual:
          - src: ./src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    sha256: {}
  googleCloudBuild:
    projectId: your-google-cloud-project-id
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}
